<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/lawlah/image/upload/v1554456517/me.jpg" alt="Ruth Ariyo">
                        <h6>Ruth Ariyo</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="http://twitter.com/melawlah" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="http://github.com/melawlah" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@melawlah" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a baker who found herself falling in love with programming, I love the combination of creative and logical problem solving skills. Along the way, I realized baking is a lot more like coding, you need to follow a particular instructions to get your desired results. I specialize in React and other skills such as HTML, CSS, Bootstrap.  </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | React </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
